### ISSUE TITLE
Replacing Mirror Delegation for Flutter 

### ISSUE THREAD

**Issue by mrdjohnson** [stevenroose/dart-reddit#11]
I have a working version of this code that removes the mirrors and JsonObjects. This allows the code to run in Flutter applications without issue.

I have not posted this yet because I am not sure how to replace your ListingResult::noSuchMethod 
```dart
  @override
  noSuchMethod(Invocation inv) => reflect(_result).delegate(inv);
```

I need to return something else instead of the reflect call.  If you have thoughts on what to do with this I'd greatly appreciate it.

**Comment by stevenroose** [comment]
I'm not sure if I remember exactly. But I think that was to make the getters work for any value. I think, if your new object implements `Map`, you can just remove that method. Instead of doing `obj.someJsonArg`, you'd have to call `obj["someJsonArg"]`.

Thanks for solving that, btw, it's been on my list for a while, but Dart stuff is not really a priority for me right now.
